# Default initial positions for nick_bot's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0.5
  joint_3: 0
  joint_4: 0
  joint_5: 0
<<<<<<< HEAD
  joint_6: 5
=======
  joint_6: -1.32996
>>>>>>> 76f5357f513dae2b293c3d1a1c9c614d014a98da
