# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_steppers_controller
    - arm_group_servos_controller
#    - hand_group_controller

  arm_group_steppers_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      
  arm_group_servos_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_4
      - joint_5
      - joint_6
      
#  hand_group_controller:
#    type: FollowJointTrajectory
#    action_ns: follow_joint_trajectory
#    default: true
#    joints:
#      - joint_6
