controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: False

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
