controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    #use_sim_time: false

    arm_group_steppers_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    arm_group_servos_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_steppers_controller:
 ros__parameters:
   joints:
     - joint_1
     - joint_2	
     - joint_3
   command_interfaces:
     - position
   state_interfaces:
     - position
      
arm_group_servos_controller:
  ros__parameters:
    joints:
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position

#hand_group_controller:
#  ros__parameters:
#    joints: 
#      - joint_6
#    command_interfaces:
#      - position
#    state_interfaces:
#      - position
#     - velocity
